language: minimal
os: linux
dist: bionic
arch: arm64
env:
  - HASURA_VERSION=1.3.3
services:
  - docker
before_install:
  - docker build --build-arg HASURA_VER=${HASURA_VERSION} -t "${DOCKER_USERNAME}/graphql-engine-arm64:${HASURA_VERSION}" -t "${DOCKER_USERNAME}/graphql-engine-arm64:latest" .
script:
  - bash docker_push
