os: linux
dist: focal
arch: arm64
env:
  - HASURA_VERSION=1.3.3 PG_CLIENT_VER=12
services:
  - docker
before_install:
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo bash -c 'echo "deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - sudo apt-get update
  - sudo apt-get install -y libncurses5 git build-essential llvm wget libnuma-dev zlib1g-dev libpq-dev postgresql-client-common postgresql-client-${PG_CLIENT_VER} libkrb5-dev libssl-dev
  - wget https://downloads.haskell.org/~ghc/8.10.1/ghc-8.10.1-aarch64-deb9-linux.tar.xz
  - wget http://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/cabal-install-3.2.0.0.tar.gz
  - tar xf ghc-8.10.1-aarch64-deb9-linux.tar.xz && tar xzf cabal-install-3.2.0.0.tar.gz
  - rm *.gz *.xz
  - cd ghc-8.10.1
  - ./configure && sudo make install
  - cd ../cabal-install-3.2.0.0
  - patch -p1 < ../ghc_8_10.patch
  - bash ./bootstrap.sh
  - git clone -b v${HASURA_VERSION} https://github.com/hasura/graphql-engine.git
script:
  - cd graphql-engine/server
  - cabal v2-update
  - cabal v2-build --ghc-options="+RTS -M3G -c -RTS -O0 -j1" -j1
