language: haskell
os: linux
dist: focal
arch: arm64
env:
  - HASURA_VERSION=1.3.3 PG_CLIENT_VER=13
services:
  - docker
before_install:
  - add-apt-repository -y ppa:hvr/ghc
  - apt-get update && apt-get install -y ghc-8.10.3 cabal-install-3.4
  - echo "deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  - apt-get update && apt-get install -y libncurses5 git build-essential llvm wget libnuma-dev zlib1g-dev libpq-dev postgresql-client-common postgresql-client-${PG_CLIENT_VER} libkrb5-dev libssl-dev
  - git clone -b v${HASURA_VERSION} https://github.com/hasura/graphql-engine.git
script:
  - cd graphql-engine/server
  - cabal v2-update
  - cabal v2-build --ghc-options="+RTS -M3G -c -RTS -O0 -j1" -j1
